# Generated by Django 4.1.5 on 2024-05-08 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_is_active', models.BooleanField(default=True)),
                ('category_created_by', models.CharField(max_length=255)),
                ('category_updated_by', models.CharField(max_length=255)),
                ('category_created_timestamp', models.DateField(default=django.utils.timezone.now)),
                ('category_updated_timestamp', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_tag', models.CharField(choices=[('SALE', 'Sale'), ('NEW', 'New'), ('HOT', 'Hot'), ('DISCOUNT', 'Discount')], default='NEW', max_length=255)),
                ('product_title', models.CharField(max_length=255)),
                ('product_seller_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_discount', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_description', models.TextField()),
                ('product_manufacturing_date', models.DateField()),
                ('product_lifespan', models.IntegerField()),
                ('product_stocks_left', models.IntegerField()),
                ('category_is_active', models.BooleanField(default=True)),
                ('category_created_by', models.CharField(max_length=255)),
                ('category_updated_by', models.CharField(max_length=255)),
                ('category_created_timestamp', models.DateField(default=django.utils.timezone.now)),
                ('category_updated_timestamp', models.DateField(default=django.utils.timezone.now)),
                ('product_category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
