# Generated by Django 5.0.6 on 2024-05-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_cart_product_remove_cart_user_id_cart_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
