# Generated by Django 5.0.6 on 2024-05-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_category_created_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image_url',
            field=models.URLField(default='abs'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_url',
            field=models.URLField(default='abs'),
        ),
    ]
