# Generated by Django 5.0.6 on 2024-05-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_title',
        ),
    ]
