# Generated by Django 5.0.6 on 2024-05-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_cart_user_id_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
