# Generated by Django 5.0.6 on 2024-05-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_product_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_created_by',
            new_name='product_created_by',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_created_timestamp',
            new_name='product_created_timestamp',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_is_active',
            new_name='product_is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_updated_by',
            new_name='product_updated_by',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_updated_timestamp',
            new_name='product_updated_timestamp',
        ),
    ]
